#
"#": D:\#\
"#Icon": D:\#Icon\
"#Lnk": D:\#Lnk\#\
"#Script": E:\Script\
"#ScriptText": E:\Project\Ahk\Config\Script.txt

# Folder:
#     Desktop:
#         Icon: 图标 | 默认目录下{#Icon}查找同名文件 \ xxx.ico \ xxx.exe
#         Name: 别名 | 默认文件夹名|自定义名 / 以$开头完整替换
#         Info: 备注 | 默认软件版本 文件夹下 {文件夹}.exe
#                     7zFM.exe | 指定软件 通过这个软件获取本本
#                          cmd | frpc.exe -v | (\d+)  | \1
#                              |  命令        | RE匹配 | RE结果
#         Rename: 文件\文件夹 名称替换
#                  Xxx   -> XXX
#                  Xxx.x -> Xxx.X
#     Lnk:
#         Name: 快捷方式名 | 默认文件夹名
#         TargetPath: 应用程序位置 | 默认{文件夹}.exe
#         WorkingDirectory: 工作文件夹 | 默认{文件夹}
#         Description: 备注信息 | 默认空
#         IconLocation: 快捷键图标 | 默认{文件夹}.exe

Default: &Default
    Desktop:
    Lnk:

$C:
    Program Files:
        Desktop:
            Name: $ProgramFiles | x64
    Program Files (x86):
        Desktop:
            Name: $ProgramFiles | x32
    ProgramData\Microsoft\Windows\Start Menu\Programs:
        Desktop:
            Name: $开始\程序 | 系统
            Rename: Immersive Control Panel.lnk | 设置

#
$D:
    7-Zip:
        Desktop:
            Name: 解压缩
            Info: 7zFM.exe
        Lnk:
            Name: 7-Zip.lnk
            TargetPath: 7zFM.exe
    Adb:
        Desktop:
            Name: 安卓工具
            Info: cmd | adb.exe --version | (Version )([\d\.]+)(\-\d+) | 2
        Lnk: Ignore
    AutoHotkey: *Default
    HuoRong:
        Desktop:
            Name: 火绒
            Info: .\Sysdiag\bin\HipsMain.exe
        Lnk:
            -   Name: HuoRong.lnk
                TargetPath: .\Sysdiag\bin\HipsMain.exe
                Description: 火绒
            -   Name: HuoRongSword.lnk
                TargetPath: .\Sysdiag\bin\HRSword.exe
                Description: 火绒剑
    Python:
        <Base>: &PythonBase
            Desktop:
                Info: cmd | python.exe --version | (Python )([\d\.]+) | 2
                Icon: Python.ico
            Lnk: Ignore
        <VirtualEnv>: &PythonVirtualEnv
            Desktop:
                Info: cmd | .\Scripts\python.exe --version | (Python )([\d\.]+) | 2
            Lnk: Ignore
        Desktop:
            Info: cmd | .\#\Scripts\python.exe --version | (Python )([\d\.]+) | 2
            Icon: Python.ico
        Lnk:
            TargetPath: .\#\Scripts\python.exe
    Python\#: *PythonVirtualEnv
    Python\#DeepLearning: *PythonVirtualEnv
    Python\2.7: *PythonBase
    Python\3.8: *PythonBase
    Python\3.9: *PythonBase
    Python\3.10: *PythonBase

#

#
Script:
    Bin:
        CMD:
            Exe: C:\Windows\System32\cmd.exe
        PS:
            Exe: D:\PowerShell\pwsh.exe
        Python:
            Exe: &Python D:\Python\#\Scripts\python.exe
    Python:
        Script:
            Exe: *Python
            Args: E:\Script\Setup.py

        Windows:
            Exe: *Python
            Args: E:\Project\script\system\windows.py
